api_platform:
    title: Hello API Platform
    version: 1.0.0
    formats:
        jsonld: [ 'application/ld+json' ]
        json: [ 'application/json' ]
        html: ['text/html']
    docs_formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        pagination_items_per_page: 12
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
